### ISSUE TITLE
Content: Update "Retro Funding + Rounds" contents based on legal requirement

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#166]
Legal has advised that we should not combine the terms "Retro Funding" with "Round". So, we need to update the following:

### Application title
Old: "Apply for Retro Funding Round 5: OP Stack"
New: "Apply for Retro Funding 5: OP Stack" (remove the word Round)

<img width="673" alt="Screenshot 2024-08-20 at 2 02 38 PM" src="https://github.com/user-attachments/assets/5cf5053b-62c0-4a4e-97cb-ffe92a8f9f42">

### Callouts
Old: "Now taking applications for Retro Funding Round 5: OP Stack"
New: "Now taking applications for Retro Funding 5: OP Stack" (remove the word Round)

<img width="845" alt="Screenshot 2024-08-20 at 2 06 16 PM" src="https://github.com/user-attachments/assets/2b2ce261-266d-4eba-80a6-f6878ff84864">

Old: "You applied to Retro Funding Round 5: OP Stack"
New: "You applied to Retro Funding 5: OP Stack"

<img width="848" alt="Screenshot 2024-08-20 at 2 06 31 PM" src="https://github.com/user-attachments/assets/5d372a2e-5a3a-4464-89ce-22272cf4364d">

**Comment by sbvhev** [comment]
@shaunop 
Ready to review
