### ISSUE TITLE
Application : Fix spacing after : in the Rules section

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#167]
**Not a P0**

There should be a space after each colon : down the rules list.

Subtext (right under "Rules") should be colored "secondary-foreground"

<img width="786" alt="Screenshot 2024-08-20 at 4 38 51 PM" src="https://github.com/user-attachments/assets/b4c93266-90f8-4b96-9ed8-7b02b3a72fa0">

**Comment by sbvhev** [comment]
@kent @shaunop 
Ready to review
