### ISSUE TITLE
Profile settings: If I don't have an email, then button should be primary and read "Save"

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#169]
**Not a P0**

If I don't have an email, then button should be primary "add email" and it should launch the add-email-modal. Currently it's an empty input with edit button. 

Staging:
<img width="960" alt="Screenshot 2024-08-20 at 4 45 57 PM" src="https://github.com/user-attachments/assets/ca873274-39fa-447a-aa40-fa7871c63e43">

Design: 
<img width="620" alt="Screenshot 2024-08-20 at 4 47 40 PM" src="https://github.com/user-attachments/assets/0b26e0ce-e3bf-4b6d-b8ad-c2b4638ee8d1">

**Comment by sbvhev** [comment]
@shaunop 
Ready to review

**Comment by shaunop** [comment]
I wasn't able to confirm this. Here's another one related to email. Thanks! https://github.com/voteagora/op-atlas/issues/255
