### ISSUE TITLE
Add Contributors modal takes on full black background (vs transparent like other modals)

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#170]
**Not a P0**

The Add Contributors modal takes on full black background (vs transparent like other modals). The modal bg should use the same visual pattern as all other modals (black with transparency). 

<img width="786" alt="Screenshot 2024-08-20 at 4 51 28 PM" src="https://github.com/user-attachments/assets/4e705591-fcbe-4b75-ae5e-6537a2bf5113">

**Comment by sbvhev** [comment]
@shaunop 
Ready to review
