### ISSUE TITLE
Add Contributors modal content update

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#171]
**Not a P0**

Subtext should read: "You can add contributors by their Farcaster username. They must have an Optimist profile."

Staging: 
<img width="786" alt="Screenshot 2024-08-20 at 4 51 28 PM" src="https://github.com/user-attachments/assets/d5ee0502-f891-42de-8efa-d163fdbc5105">

**Comment by sbvhev** [comment]
@shaunop 
Ready to review
