### ISSUE TITLE
Add Contributors vs Add Team Members

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#172]
**Not a P0.** 

Organizations have "team members".
Projects have "contributors". 

In the Make an Organization modal flow, the content should be "team members" not contributors. 

Staging:
<img width="810" alt="Screenshot 2024-08-20 at 4 58 05 PM" src="https://github.com/user-attachments/assets/0994ef76-4684-4c80-b792-05c622565a6e">

Design:
<img width="481" alt="Screenshot 2024-08-20 at 4 54 50 PM" src="https://github.com/user-attachments/assets/a7337aa6-28f2-44de-a3c7-b2c80e84c6a1">

**Comment by sbvhev** [comment]
@shaunop 
Ready for review
