### ISSUE TITLE
Hide the stand alone "add your first project" entry point if Org exists

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#174]
If you've made an Org, then the stand alone "add your first project" entry point should be hidden. User proceeds to add project under the org. If user wished to start by adding a project separate from an org, they can do that via the ••• more menu (note that this way my oversight and not communicated clearly, apologies).
 
Staging:
<img width="600" alt="Screenshot 2024-08-20 at 8 32 11 PM" src="https://github.com/user-attachments/assets/56320a1d-8656-4498-834b-b7caa316efe4">

Design: 
<img width="600" alt="Screenshot 2024-08-20 at 8 41 52 PM" src="https://github.com/user-attachments/assets/e0d13061-7d34-4490-b1d6-5dfd30c16c30">
If user adds a project via more menu, it is defaulted to "no organization" in the project setup.

**Comment by sbvhev** [comment]
@shaunop 
Ready to review
