### ISSUE TITLE
Download sharing image from success callout is the wrong image

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#175]
I hit the download button from this callout:
<img width="441" alt="Screenshot 2024-08-20 at 8 45 10 PM" src="https://github.com/user-attachments/assets/50c56354-ab11-425c-8617-1f21077486d3">
And it downloaded this image:
![organization-create-graphic (1)](https://github.com/user-attachments/assets/97308a50-6988-4c7b-9956-a1dd73a69b2d)

However, it should be downloading the "I submitted..." retro funding image.
![RetroFunding_R5_Submission_Image](https://github.com/user-attachments/assets/172e801f-d00d-42da-b37c-f249a2f58033)

**Comment by sbvhev** [comment]
@shaunop 
Ready to review
