### ISSUE TITLE
Rounds Tab: Round 5 card should show 8M OP (Not 10M OP)

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#185]
On the round 5 card (Rounds tab): 
1. the OP amount should be 8M not 10M. 
2. the apply by date should be Sep 5

<img width="799" alt="Screenshot 2024-08-21 at 5 37 38 PM" src="https://github.com/user-attachments/assets/7c1001ad-c0af-4730-8f43-5c80299d51b2">

**Comment by sbvhev** [comment]
@shaunop 
Ready to review

**Comment by shaunop** [comment]
Looks good!
