### ISSUE TITLE
Fix autogeneration of sharable graphic for results and grant claiming

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#192]
We cut this scope for r4 grant claiming and results. This feature helps us increase the reach of Retro Funding 

Designs [here](https://www.figma.com/design/ahqDNoZtRWYmesgEyLJo6B/Claim-Flow?node-id=0-1&t=zglyV1p5CDpQjoN0-1)

**Comment by shaunop** [comment]
Designs for Rd5 image [here. ](https://www.figma.com/design/ahqDNoZtRWYmesgEyLJo6B/Claim-Flow?node-id=703-17077&t=9qh3JZYun8erHWuK-1)

Preview: 
![RetroFunding_R5_Receipt_1](https://github.com/user-attachments/assets/99153659-ac43-42b0-9563-5bf2245c503d)
![RetroFunding_R5_Receipt_2](https://github.com/user-attachments/assets/40b5bd64-42d8-41ec-9086-ea02897a1257)
![RetroFunding_R5_Receipt_3](https://github.com/user-attachments/assets/6214aa7f-38bb-44e3-b5b8-b40bf7b8d6da)

@JSeiferth
