### ISSUE TITLE
Project Creation - Repos and Links doesn't allow me to proceed

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#203]
**Describe the bug**
I added a repo and verified it. After saving and clicking "next" I don't get the green checkmark on this page. The verify button is still available, when I try to verify again it says "you already verified this repo"

**To Reproduce**
1. Add repo and go through verification flow
2. Click "Save" or "next"
3. See that page doesn't show as confirmed (e.g. green checkmark on the side) and that the "verify" button is still active

**Expected behavior**
Page is checkmarked after repo has been added and verified

**Screenshots**
<img width="942" alt="Screenshot 2024-08-23 at 15 17 22" src="https://github.com/user-attachments/assets/ea89554f-0f97-48cf-9b06-913efd4eb55e">
<img width="502" alt="Screenshot 2024-08-23 at 15 17 54" src="https://github.com/user-attachments/assets/5e145ba6-53e8-4dd2-beeb-5c73c1061a85">

**Comment by JSeiferth** [comment]
I tried this again with a different repo and encountered the same issue 
<img width="1088" alt="Screenshot 2024-08-23 at 15 20 36" src="https://github.com/user-attachments/assets/a7147f75-4a1a-4b6f-9748-b92ac02b32af">

**Comment by JSeiferth** [comment]
This issue also seems to apply to contracts @stepandel 

![Image](https://github.com/user-attachments/assets/bd5b530b-6ac3-4f60-a22f-03a580f3699a)

**Comment by JSeiferth** [comment]
A user has reported the same issue

<img width="667" alt="Screenshot 2024-08-23 at 16 32 09" src="https://github.com/user-attachments/assets/1a5b71b1-c9cb-4150-ab5b-040d741137a2">

**Comment by stepandel** [comment]
> A user has reported the same issue
> 
Seems like they just didn't add the verification file to the repo. Different issue?

**Comment by JSeiferth** [comment]
Same issue apparently, here's the repo with the valid json https://github.com/optimism-java/hildr

**Comment by JSeiferth** [comment]
Issue is resolved from my side - will further check with the user
