### ISSUE TITLE
Unable to edit application

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#204]
**Describe the bug**
I'm not able to edit a submitted application. Is this missing from designs and scope?

**Comment by JSeiferth** [comment]
Designs for editing application [here](https://www.figma.com/design/K4GCS7m723bMvfOVNPlGev/OP-Atlas-Updates-for-Round-5?node-id=762-67675&t=AyKa6spAjkav5G9w-4)

**Comment by shaunop** [comment]
Users returning to the application should see the content they've already input. They should have the option to open/reveal each project (using the chevron) and then edit their inputs. If they make edits, they should be able to select T&C's again and resubmit.
