### ISSUE TITLE
Links are not saved within Project Metadata

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#205]
**Describe the bug**
After adding a link within the "Repos and links" page, saving the page and publishing metadata. The link I added does not show within the project metadata
- Attestation [here](https://storage.retrofunding.optimism.io/ipfs/QmQffvyvPDEsHL6Pord8ry138FAAK8RTrkhPyhrd5tghSe) 
- Metadata [here](https://storage.retrofunding.optimism.io/ipfs/QmQffvyvPDEsHL6Pord8ry138FAAK8RTrkhPyhrd5tghSe)

<img width="853" alt="Screenshot 2024-08-23 at 16 09 39" src="https://github.com/user-attachments/assets/17558d22-9aa7-4721-a41c-c7a4bb720886">

**Comment by stepandel** [comment]
Seems to be working now
