### ISSUE TITLE
Can't use "add another link" - Repos & Links Page at project creation

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#207]
**Describe the bug**
Can't click "add another link" unless I save the project, go to the next page and come back to the previous page. 

https://github.com/user-attachments/assets/4a7c277e-1e14-4c4d-93b1-15f4e272ddff

**Comment by stepandel** [comment]
I'm lower the priority of this one. users can still add links so long as they save the previous one.
Ideally we'd want a remove link button as well
