### ISSUE TITLE
Image in the "Welcome to Retro Funding App" card is pixelated

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#224]
**Describe the bug**
The image in the "Welcome to Retro Funding App" card is pixelated. Please replace with clear image: 

Screenshot: 
<img width="489" alt="Screenshot 2024-08-26 at 4 50 37 PM" src="https://github.com/user-attachments/assets/963c87ab-536a-4928-8161-0a798ecbe3fe">

Asset:

<img width="216" alt="sunnies-combined-image" src="https://github.com/user-attachments/assets/2d36f0c0-b991-4034-82e5-00dca99ea1f4">

**Comment by sbvhev** [comment]
@shaunop  ready to review

**Comment by shaunop** [comment]
How do I review? I don't see any change on retrofunding.io
