### ISSUE TITLE
Submitted projects disappear from the dashboard

### ISSUE THREAD

**Issue by GrapeBaBa** [voteagora/op-atlas#239]
I encountered a serious problem in the process of applying for retro funding 5. I have a project **hildr** that has been successfully submitted (https://retrolist.app/project/0x7333cac46b20999de07f4d7be5146c10a30f19586907bd2ce986b81af340cb97), and the information has actually been successfully uploaded to the chain. I wanted to modify the information yesterday, but found that the project no longer exists on the application website (https://retrofunding.optimism.io/dashboard), and it seems to have been deleted, as shown in the screenshot below. I would like to ask what this problem is and how I can deal with it.

I want to confirm whether this situation will affect subsequent voting, because the project can no longer be seen on the application website (https://retrofunding.optimism.io/).

If I need to resubmit, I feel that there will be two identical projects in the list of successfully submitted projects. Who can help me delete the previous one? Also there is another problem which the repo already verified, so that resubmit will failed.

Because the deadline is approaching, please help as soon as possible, thank you very much.

![image](https://github.com/user-attachments/assets/b885f785-2225-4e21-9e78-900e5f6379a0)

**Comment by GrapeBaBa** [comment]
#213 is also I came across, and you can see the project **hildr** in my screenshot before.

**Comment by GrapeBaBa** [comment]
Oh, I found that I can actually go to the details page of hildr through the link https://retrofunding.optimism.io/projects/0x7333cac46b20999de07f4d7be5146c10a30f19586907bd2ce986b81af340cb97/publish . Most likely a display problem.

**Comment by stepandel** [comment]
seems like you or one of your team members accidentally deleted the project. Just restored it.
