### ISSUE TITLE
Testing improvements: Allow us to test different user states

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#242]
We need to be able to test a bunch of different user journey, like KYC, citizenship profile creation, etc. etc.

**Comment by JSeiferth** [comment]
How do we make it easy to test different product states? 

Loom tutorial to set users into different states in the database. @kent to circle back how to do this. Update following next week. 
R6 will include this testing

**Comment by kent** [comment]
Shared the Loom and access with you via DM!
