### ISSUE TITLE
Application: "view our guidelines" link should go to forum post

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#268]
Application, projects and impact step: "view our guidelines" link should go to forum post. @JSeiferth do we have a post going up? Like we did in previous rounds: https://gov.optimism.io/t/retro-funding-4-onchain-builder-application-guidelines/8165

If not, we should remove the link and last sentence. The subtext can simply read:

> This part of your application helps badgeholders understand how your work has benefitted the Optimism Collective.

Screenshot:
<img width="926" alt="Screenshot 2024-09-27 at 2 32 20 PM" src="https://github.com/user-attachments/assets/1879d771-a1c0-41bb-b75e-7904670932de">

**Comment by kent** [comment]
@JSeiferth can you post the link here?

**Comment by mcgingras** [comment]
removed the link.
