### ISSUE TITLE
Results announce: Banner on the landing page is outdatedd

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#295]
Banner talks about Retro Funding 4 results

<img width="1512" alt="Screenshot 2024-10-09 at 19 03 54" src="https://github.com/user-attachments/assets/9c04af02-2f33-4173-9438-6f6c6b30cbcb">

**Comment by shaunop** [comment]
Copy should be: The results are in! Sign in to see your Retro Funding 5 results.
