### ISSUE TITLE
Commas are missing in the downloaded share graphic

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#311]
Commas are present in the web preview of the share graphic, but they are missing in the downloaded share graphic. We can also remove the word received (project name "received") from the downloaded graphic.

Web screenshot:
<img width="811" alt="Screenshot 2024-10-15 at 12 17 14 PM" src="https://github.com/user-attachments/assets/e6e088c2-d9d2-4ed5-80b8-de537bc78f67">

Downloaded graphic: 
![reward-c5fgyp](https://github.com/user-attachments/assets/84de67f1-040c-42c7-b047-de0754bdfbe3)

**Comment by stepandel** [comment]
fixed by 5c8525b396e23e6e5f48391f6aa644a8b13b0824
