### ISSUE TITLE
Remove the subtext "This step is required to apply for Retro Funding." from the add email modal. 

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#367]
Remove the subtext "This step is required to apply for Retro Funding." from the add email modal. 

<img width="469" alt="Screenshot 2024-12-06 at 1 48 47 PM" src="https://github.com/user-attachments/assets/a813a022-8ff0-4a09-ba04-f843b4cf7fa3">

[Figma](https://www.figma.com/design/G20NIC9PENiNZvfxY1sl6G/OP-Atlas-Profiles?node-id=192-22650&t=JOelIFrCbrHxnQbm-1)

**Comment by stepandel** [comment]
@shaunop I think we should we leave this -- we will have hard time collecting emails for Retro Funding recipients.
Maybe we should change to "This step is required to be eligible for Retro Funding"
