### ISSUE TITLE
User Profile header section

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#370]
User Profile header section
- [x] Avatar (from FID)
- [x] Display name (from FID)
- [x] Bio (from FID)

User profile social badges: 
- [ ] Farcaster w/ follower count (from FID)
- [ ] Twitter w / follower count (from FID)
- [ ] GitHub w / follower count (from Atlas)
- [x] Agora w / delegator count (from connected delegate wallet address)
- [x] Collective Forum (from Atlas)
- [x] Add tooltips when hovering over social badges to communicate name of platform (ie Farcaster, Optimism Agora, etc)

[Figma](https://www.figma.com/design/G20NIC9PENiNZvfxY1sl6G/OP-Atlas-Profiles?node-id=192-22650&t=JOelIFrCbrHxnQbm-1)

**Comment by shaunop** [comment]
12.17
- [ ] Badge background color should be "secondary" (#F2F3F8)

**Comment by stepandel** [comment]
![CleanShot 2024-12-17 at 16 47 18@2x](https://github.com/user-attachments/assets/80f1f9b3-9bdb-4da4-b4fe-ebe3afc3ea94)
@shaunop

**Comment by shaunop** [comment]
Thanks @stepandel it's close but not quite right. I wonder if your line heights are the same as what I've got in the design system? Here's a comparison of the design (on the left) and the build (on the right)

<img width="432" alt="Screenshot 2024-12-17 at 5 50 23 PM" src="https://github.com/user-attachments/assets/b538ed25-a75c-41aa-88df-5a75d9649214" />
