### ISSUE TITLE
Organization Profile header section

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#371]
Organization Profile header section
- [x] Cover image (from Atlas)
- [x] Avatar (from Atlas)
- [x] Display name (from Atlas)
- [x] "Organization" badge next to display name 
- [x] Bio (from Atlas)

Social badges: 
- [x] Links (from Atlas)
- [ ] Farcaster w / follower count (from Atlas)
- [ ] Twitter w / follower count (from Atlas)
- [ ] Mirror (from Atlas)
- [x] Add tooltips when hovering over social badges to communicate name of platform (ie Farcaster, Mirror, etc)

[Figma](https://www.figma.com/design/G20NIC9PENiNZvfxY1sl6G/OP-Atlas-Profiles?node-id=192-22650&t=JOelIFrCbrHxnQbm-1)

**Comment by shaunop** [comment]
12.17
- [ ] "Organization" badge looks too small. Should be large styles (28px h, font: 'small'-inter, med, 14/20")

Screenshot: 
<img width="543" alt="Screenshot 2024-12-17 at 1 35 42 PM" src="https://github.com/user-attachments/assets/6e3d6e6d-0828-4c96-acfb-42871acfd662" />

Design:
<img width="324" alt="Screenshot 2024-12-17 at 1 32 54 PM" src="https://github.com/user-attachments/assets/84e9bd80-82b2-44e5-86ca-71fa283ed255" />

**Comment by shaunop** [comment]
12.17 
When links don't have "name", we show URL. If URL, then...
- [ ] Don't show "https://" in links
- [ ] Truncate after 30 characters

Screenshot of build:
<img width="893" alt="Screenshot 2024-12-17 at 1 37 04 PM" src="https://github.com/user-attachments/assets/f9048c8b-316e-41be-a05e-f4a33336ef03" />

**Comment by shaunop** [comment]
12.17
- [ ] Org bio should truncate after 3 lines, then provide text-button to "read more". When bio is expanded, the text button should say "read less" 
- [ ] Bio text color should be "secondary-foreground"

Build:
<img width="948" alt="Screenshot 2024-12-17 at 2 03 18 PM" src="https://github.com/user-attachments/assets/f4a70db6-1aaa-4bde-a23b-55c54f4ef5e0" />

Design:
<img width="842" alt="Screenshot 2024-12-17 at 2 02 09 PM" src="https://github.com/user-attachments/assets/b06006dd-d49e-448e-9b4d-2317bf3279a1" />

**Comment by stepandel** [comment]
closing this. Remaining issue: https://github.com/voteagora/op-atlas/issues/404
