### ISSUE TITLE
Organizations and Projects list views

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#375]
Organizations and Projects list views
- [x] Show organizations a user is a team member of; link out to Organization Profile
- [x] Show projects a user is contributor of, link out to project profile on RetroList https://retrolist.app/
- [x] On Organization profiles > show organizations projects, link out to project profile on RetroList https://retrolist.app/
- [x] If project received Retro Funding, show text
- [x] On hover, reveal outbound arrow icons

<img width="698" alt="Screenshot 2024-12-06 at 2 29 07 PM" src="https://github.com/user-attachments/assets/0c0329a2-4bb3-4342-9909-9e6e264e52ae">

**Comment by stepandel** [comment]
@shaunop I'm linking organizations to their page on Atlas instead
