### ISSUE TITLE
Remove "Now taking applications" modal when Adding New Project

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#381]
This modal needs to be removed. It appears when a user clicks to "add a project"

<img width="742" alt="Screenshot 2024-12-09 at 2 52 59 PM" src="https://github.com/user-attachments/assets/9304a589-4de6-4097-8a90-1e6fb5d47385">

**Comment by JSeiferth** [comment]
Duplicate of https://github.com/voteagora/op-atlas/issues/345
