### ISSUE TITLE
OP Stack Proximity card fixes and polish

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#398]
Some links in the OP Stack Proximity card are incorrect or broken:
- [x] OSO link should be: https://www.opensource.observer/
- [x] Forum post link should be: https://gov.optimism.io/t/retro-funding-5-guest-voter-selection-algorithm-explanation/8719

Card styling needs work:
- [x] Card corner radius should be 12pt
- [x] Title should be aligned to top left corner of inner card
- [x] Subtext (github username) should be style "p" and color "secondary-foreground" 
- [x] Description text style should be "alt/small" (inter 14/20 regular) and color ""secondary-foreground" 
- [x] Badge in upper right corner looks small, should be size "default"

If 100th percentile...
- [x] Title should still read "...ranks in the top 1% of developers..."

<img width="910" alt="Screenshot 2024-12-17 at 2 47 06 PM" src="https://github.com/user-attachments/assets/dfe09f46-0f29-4b6f-925d-da32a9d7b763" />

**Comment by shaunop** [comment]
Could you share screen shots of folks in different percentiles to verify the UI? @stepandel

**Comment by stepandel** [comment]
![CleanShot 2024-12-17 at 16 55 42@2x](https://github.com/user-attachments/assets/0c6661a4-501d-414f-9940-deaccc2a5fbc)
![CleanShot 2024-12-17 at 17 01 26@2x](https://github.com/user-attachments/assets/d5783bd6-ddc4-413d-a40b-5e5be65207cd)
![CleanShot 2024-12-17 at 17 04 01@2x](https://github.com/user-attachments/assets/dfd5876b-8fe5-49d4-a652-8e32466c07e3)

**Comment by stepandel** [comment]
^ are no longer accurate -- I pushed some fixed
