### ISSUE TITLE
Election Profiles: Project Links

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#410]
**Describe the bug**
On the OP Profile
1. Some projects have clickable links while others don't
2. The link symbol is inconsistent (project have the error callout while projects don't)

**To Reproduce**
Go to https://retrofunding.optimism.io/jonassft and see "Julian test project" and "dwada..." are not linked. 
+ notice that projects have an error symbol and orgs don't

https://github.com/user-attachments/assets/0669b0b3-a3c9-4e84-8c63-f900e78d1769

**Comment by stepandel** [comment]
1. The projects that didn't apply for retro funding do not have a link to Retrolist (because they only index RF applicants)
2. Organization links are inbound while projects are outbound.

Link style improvements are tracked [here](https://github.com/voteagora/op-atlas/issues/402)
